import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {


  Questions: any[] = [
  {
    "Timestamp": "2020/10/16 2:37:13 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20173552,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "ENSIM'Elec",
    "5-Plutôt...": "Apple;Android",
    "6-Quel est ton personnage de fiction préféré ?": "TRUITEMan",
    "7-Que fais-tu de ton temps libre ?": "Musculation jeux vidéos ",
    "8-Quels sont tes films": {
      "séries préférées ?": "Prison Break"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;HTML5 CSS;Php;Python;Assembleur",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Linux]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Mac]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Un peu",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Un peu",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Un peu",
    "13-Que penses-tu de ? [Visual studio]": "J'aime bien",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "J'aime bien",
    "13-Que penses-tu de ? [UnrealEngine]": "J'aime bien",
    "13-Que penses-tu de ? [SublimeText]": "J'aime bien",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Connais pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:37:18 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20181588,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Jensim;ENSIM is running;ENSIM'Elec",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Dark Vador",
    "7-Que fais-tu de ton temps libre ?": "Conservatoire",
    "8-Quels sont tes films": {
      "séries préférées ?": "Avengers"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;C++;HTML5 CSS;Php;Python;JavaScript",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Régulièrement"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Jamais",
    "11-As-tu déjà utilisé ? [Linux]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Un peu",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Régulièrement",
    "13-Que penses-tu de ? [Visual studio]": "Je suis fan",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "J'aime bien",
    "13-Que penses-tu de ? [Eclipse]": "Je n'aime pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Je n'aime pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Je suis fan",
    "13-Que penses-tu de ? [Atom]": "J'aime bien",
    "13-Que penses-tu de ? [Anaconda]": "Je suis fan",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:39:33 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20202834,
    "2-D'où viens tu ?": "Bretagne",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "DUT;Licence",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDE;Abobinables",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Batman",
    "7-Que fais-tu de ton temps libre ?": "Je vois des potes",
    "8-Quels sont tes films": {
      "séries préférées ?": "Breaking bad"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;HTML5 CSS;Php;Python;JavaScript;Assembleur",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Un peu",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Un peu",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Un peu",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Un peu",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Un peu",
    "13-Que penses-tu de ? [Visual studio]": "Je n'aime pas",
    "13-Que penses-tu de ? [NotePad++]": "Je suis fan",
    "13-Que penses-tu de ? [Codblock]": "Je n'aime pas",
    "13-Que penses-tu de ? [AndroidStudio]": "J'aime bien",
    "13-Que penses-tu de ? [Eclipse]": "J'aime bien",
    "13-Que penses-tu de ? [IntellJ]": "J'aime bien",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "J'aime bien",
    "13-Que penses-tu de ? [UnrealEngine]": "J'aime bien",
    "13-Que penses-tu de ? [SublimeText]": "Je suis fan",
    "13-Que penses-tu de ? [Atom]": "Je n'aime pas",
    "13-Que penses-tu de ? [Anaconda]": "Je n'aime pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:39:53 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20181973,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Infographie;ENSIM is running",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Thomas Shelby",
    "7-Que fais-tu de ton temps libre ?": "Se perdre sur youtube",
    "8-Quels sont tes films": {
      "séries préférées ?": "Peaky blinders, Breaking bad, Inception, interstellar"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome;Firefox;Edge",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;HTML5 CSS;Python;JavaScript",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Un peu",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "J'aime bien",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "Je n'aime pas",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "J'aime bien",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Je suis fan",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "J'aime bien",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:40:04 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 182457,
    "2-D'où viens tu ?": "France;Occitanie",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDE;Cultu;Infographie;MAO;ENSIMIEN;ENSIM is running;VASI;ENSIM'Elec",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Luffy",
    "7-Que fais-tu de ton temps libre ?": "Ne3ess",
    "8-Quels sont tes films": {
      "séries préférées ?": "Peaky Blinders, Got, les animes en general"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;C++;HTML5 CSS;Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu;Régulièrement"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Linux]": "Jamais",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Un peu",
    "12-As-tu déjà réalisé ? [Des logos]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Un robot]": "Un peu",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Un peu",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Un peu",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas;J'aime bien",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "Je suis fan",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Je suis fan",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "J'aime bien",
    "13-Que penses-tu de ? [SublimeText]": "J'aime bien",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "J'aime bien",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:40:23 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20173172,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "K'verne;Trublions du Plateau",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Le biberon des imbibés",
    "7-Que fais-tu de ton temps libre ?": "Je chill ",
    "8-Quels sont tes films": {
      "séries préférées ?": "Rick et morty"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;HTML5 CSS;Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Un peu",
    "11-As-tu déjà utilisé ? [Mac]": "Un peu",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Un peu",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "Je n'aime pas",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "J'aime bien",
    "13-Que penses-tu de ? [Anaconda]": "Je suis fan",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:40:30 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20182566,
    "2-D'où viens tu ?": "Maurice",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Infographie;ENSIMIEN",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Roland of Gilead",
    "7-Que fais-tu de ton temps libre ?": "Musique, ecriture, lecture... ",
    "8-Quels sont tes films": {
      "séries préférées ?": "Peaky Blinders, Daredevil, inception"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;HTML5 CSS;Php;Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Linux]": "Jamais",
    "11-As-tu déjà utilisé ? [Mac]": "Un peu",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Un peu",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Je n'aime pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Je n'aime pas",
    "13-Que penses-tu de ? [Unity]": "J'aime bien",
    "13-Que penses-tu de ? [UnrealEngine]": "J'aime bien",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Je n'aime pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:40:32 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20205905,
    "2-D'où viens tu ?": "Maroc",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Licence",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Infographie;MAO",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Aucune idée ",
    "7-Que fais-tu de ton temps libre ?": "Jeux vidéos ",
    "8-Quels sont tes films": {
      "séries préférées ?": "Prison break"
    },
    "9-Quel est ton navigateur préféré ?": "Opera",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;HTML5 CSS;Php;Python;JavaScript;Assembleur",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Jamais"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Un peu",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "Je n'aime pas",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "J'aime bien",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "J'aime bien",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "J'aime bien",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:40:53 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20171421,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Trublions du Plateau",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Kirby",
    "7-Que fais-tu de ton temps libre ?": "Lecture",
    "8-Quels sont tes films": {
      "séries préférées ?": "Steven universe"
    },
    "9-Quel est ton navigateur préféré ?": "Firefox",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;HTML5 CSS;Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Jamais",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "J'aime bien",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:41:13 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20183990,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDLC;Jensim;ENSIM'Elec",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Zeldo",
    "7-Que fais-tu de ton temps libre ?": "Je dors ",
    "8-Quels sont tes films": {
      "séries préférées ?": "En series stranger things et the oa"
    },
    "9-Quel est ton navigateur préféré ?": "Firefox",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;HTML5 CSS;Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Linux]": "Jamais",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Un peu",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Un peu",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Je n'aime pas",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "J'aime bien",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "J'aime bien",
    "13-Que penses-tu de ? [UnrealEngine]": "J'aime bien",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Connais pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:41:30 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20180975,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "DUT",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "ENSIM is running",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Link ",
    "7-Que fais-tu de ton temps libre ?": "Je joue et je programme ",
    "8-Quels sont tes films": {
      "séries préférées ?": "Battle Royale , Star Wars , Marvel "
    },
    "9-Quel est ton navigateur préféré ?": "Opera;Opéra GX ( c pour les gamers ) ",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;C++;C#;HTML5 CSS;Php;Python;JavaScript;Assembleur",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Linux]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Un peu",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Un peu",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Un peu",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Un peu",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Un peu",
    "13-Que penses-tu de ? [Visual studio]": "Je suis fan",
    "13-Que penses-tu de ? [NotePad++]": "Je n'aime pas",
    "13-Que penses-tu de ? [Codblock]": "Je n'aime pas",
    "13-Que penses-tu de ? [AndroidStudio]": "J'aime bien",
    "13-Que penses-tu de ? [Eclipse]": "Je suis fan",
    "13-Que penses-tu de ? [IntellJ]": "J'aime bien",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Je suis fan",
    "13-Que penses-tu de ? [UnrealEngine]": "Je n'aime pas",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Je suis fan",
    "13-Que penses-tu de ? [Anaconda]": "Je n'aime pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:41:39 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20171166,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Oui;915",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDE;Trublions du Plateau;ENSIM'Elec",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Vivien Reid",
    "7-Que fais-tu de ton temps libre ?": "Magic // Ultimate frisbee",
    "8-Quels sont tes films": {
      "séries préférées ?": "Retour vers le futur / Hunger games / ..."
    },
    "9-Quel est ton navigateur préféré ?": "Firefox",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Linux]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Un peu",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Un peu",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Je n'aime pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:41:42 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 205196,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa classique",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Trublions du Plateau;ENSIM'Elec",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Lucky Luke",
    "7-Que fais-tu de ton temps libre ?": "Des timelapses",
    "8-Quels sont tes films": {
      "séries préférées ?": "Rick et Morty"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;C#;HTML5 CSS;Python;JavaScript",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Linux]": "Un peu",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Un peu",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Un peu",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Un peu",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "J'aime bien",
    "13-Que penses-tu de ? [NotePad++]": "Connais pas",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "J'aime bien",
    "13-Que penses-tu de ? [Anaconda]": "J'aime bien",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:43:08 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20181916,
    "2-D'où viens tu ?": "Sri Lanka",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDE;Infographie;MAO;KFET;Abobinables",
    "5-Plutôt...": "Apple",
    "6-Quel est ton personnage de fiction préféré ?": "Diego de Umbrella Academy ",
    "7-Que fais-tu de ton temps libre ?": "Musique, Graphisme, Skate et sortir",
    "8-Quels sont tes films": {
      "séries préférées ?": "Umbrella Academy, End of the fucking World, Orphan Black Gatsby le magnifique "
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;HTML5 CSS;Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Linux]": "Un peu",
    "11-As-tu déjà utilisé ? [Mac]": "Un peu",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Un peu",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "J'aime bien",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas;J'aime bien",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "J'aime bien",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Je suis fan",
    "13-Que penses-tu de ? [Atom]": "Je suis fan",
    "13-Que penses-tu de ? [Anaconda]": "J'aime bien",
    "13-Que penses-tu de ? [Ionic]": "J'aime bien"
  },
  {
    "Timestamp": "2020/10/16 2:45:32 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20202907,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prepa BL",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Oui;970",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDLC;Cultu;K'verne",
    "5-Plutôt...": "Apple",
    "6-Quel est ton personnage de fiction préféré ?": "Nausicaa de la vallée du vent",
    "7-Que fais-tu de ton temps libre ?": "Je dessine et je lis",
    "8-Quels sont tes films": {
      "séries préférées ?": "Out of Africa/Peaky Blinders"
    },
    "9-Quel est ton navigateur préféré ?": "Safari",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;C++",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Jamais"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Mac]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Windows]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "Connais pas",
    "13-Que penses-tu de ? [Codblock]": "Je n'aime pas;J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Connais pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:45:43 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20205316,
    "2-D'où viens tu ?": "Bretagne",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prepa BL",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDLC;Jensim;MAO;GALA;K'verne;Trublions du Plateau",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Diane (dans Bojack Horseman)",
    "7-Que fais-tu de ton temps libre ?": "J'écoute de la musique et je jardine",
    "8-Quels sont tes films": {
      "séries préférées ?": "The magicians, dark, into the wild, Amélie Poulain"
    },
    "9-Quel est ton navigateur préféré ?": "Edge",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "HTML5 CSS",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Jamais"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Linux]": "Jamais",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "Connais pas",
    "13-Que penses-tu de ? [Codblock]": "Connais pas",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Connais pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:49:10 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20205471,
    "2-D'où viens tu ?": "Cameroun",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDE;Infographie",
    "5-Plutôt...": "Apple",
    "6-Quel est ton personnage de fiction préféré ?": "Sangoku",
    "7-Que fais-tu de ton temps libre ?": "Sport",
    "8-Quels sont tes films": {
      "séries préférées ?": "Breaking Bad"
    },
    "9-Quel est ton navigateur préféré ?": "Firefox",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;HTML5 CSS;Php;JavaScript",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Jamais"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Un peu",
    "11-As-tu déjà utilisé ? [Mac]": "Un peu",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Un peu",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Je suis fan",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "J'aime bien",
    "13-Que penses-tu de ? [Eclipse]": "J'aime bien",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "J'aime bien",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Je n'aime pas",
    "13-Que penses-tu de ? [Ionic]": "J'aime bien"
  },
  {
    "Timestamp": "2020/10/16 2:49:36 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20205276,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prepa BL",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "980",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDE;BDLC;Jensim;Infographie;GALA;KFET;Trublions du Plateau;ENSIM'Elec",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Mara des Acoma (Guerres de la faille, Raymond E. FEIST)",
    "7-Que fais-tu de ton temps libre ?": "Discuter, dessiner, écrire, grimper, nager, lire, ecouter de la musique (beaucoup), glander, des maths, jeux videos, roller, VTT, courir, penser, observer, aider, traîner sur YouTube...",
    "8-Quels sont tes films": {
      "séries préférées ?": "Fringe (serie), Enigma, Porco Rosso..."
    },
    "9-Quel est ton navigateur préféré ?": "Firefox;Ghostery",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;HTML5 CSS;Assembleur",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Linux]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Mac]": "Un peu",
    "11-As-tu déjà utilisé ? [Windows]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Un peu",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Un peu",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Un peu",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Un peu",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Un peu",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Je n'aime pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Connais pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 2:51:32 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20184054,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Jensim",
    "5-Plutôt...": "Apple",
    "6-Quel est ton personnage de fiction préféré ?": "Guts de Berserk",
    "7-Que fais-tu de ton temps libre ?": "Je m’instruis ",
    "8-Quels sont tes films": {
      "séries préférées ?": "Altered Carbon, Black Mirror, Shutter Island, Minority Report"
    },
    "9-Quel est ton navigateur préféré ?": "Firefox",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Un peu",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "Je n'aime pas",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Je suis fan",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Connais pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 3:00:47 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20202842,
    "2-D'où viens tu ?": "Vietnam",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Oui",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Jensim;Infographie",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Spiderman",
    "7-Que fais-tu de ton temps libre ?": "Jouer aux jeux videos",
    "8-Quels sont tes films": {
      "séries préférées ?": "Des film d'action"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;C++;C#;HTML5 CSS",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Linux]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Mac]": "Un peu",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Un peu",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "J'aime bien",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "Je n'aime pas",
    "13-Que penses-tu de ? [AndroidStudio]": "J'aime bien",
    "13-Que penses-tu de ? [Eclipse]": "J'aime bien",
    "13-Que penses-tu de ? [IntellJ]": "J'aime bien",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Je n'aime pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "J'aime bien",
    "13-Que penses-tu de ? [Atom]": "Je n'aime pas",
    "13-Que penses-tu de ? [Anaconda]": "Je n'aime pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 3:04:00 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 206001,
    "2-D'où viens tu ?": "Maroc",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa classique",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDE;BDLC;Cultu;Jensim;Infographie;MAO;GALA;ENSIMIEN;KFET;ENSIM is running;K'verne;Trublions du Plateau;VASI;ENSIM'Elec;Abobinables",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Naruto",
    "7-Que fais-tu de ton temps libre ?": "Uhm uhm you know .... ...................................................des animes manhwas mangas league of legends",
    "8-Quels sont tes films": {
      "séries préférées ?": "The wolf of wallstreet / Dark"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Jamais"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Jamais",
    "11-As-tu déjà utilisé ? [Linux]": "Un peu",
    "11-As-tu déjà utilisé ? [Mac]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Windows]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "Connais pas",
    "13-Que penses-tu de ? [Codblock]": "Connais pas",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Connais pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 3:04:28 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20205217,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prepa TSI",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Je ne sais pas encore. ",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Hachiman Hikigaya from Oregairu.",
    "7-Que fais-tu de ton temps libre ?": "Jeux vidéos et animés japonais. ",
    "8-Quels sont tes films": {
      "séries préférées ?": "Breaking Bad, The Walking Dead, Game of Thrones. "
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Jamais",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Un peu",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "Je n'aime pas",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "J'aime bien",
    "13-Que penses-tu de ? [UnrealEngine]": "J'aime bien",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Connais pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 3:56:57 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 205468,
    "2-D'où viens tu ?": "Maroc",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "DUT",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDE;BDLC;Cultu;Jensim;Infographie;MAO;GALA;ENSIMIEN;KFET;ENSIM is running;K'verne;Trublions du Plateau;VASI;ENSIM'Elec;Abobinables",
    "5-Plutôt...": "Apple",
    "6-Quel est ton personnage de fiction préféré ?": "Lucifer",
    "7-Que fais-tu de ton temps libre ?": "Sortir,dormir,améliorer mes compétences dans ce que j’aime faire, créer des apllications",
    "8-Quels sont tes films": {
      "séries préférées ?": "Breaking bad"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;HTML5 CSS;JavaScript",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Jamais"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Jamais",
    "11-As-tu déjà utilisé ? [Linux]": "Un peu",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Jamais;Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Je suis fan",
    "13-Que penses-tu de ? [NotePad++]": "Je n'aime pas",
    "13-Que penses-tu de ? [Codblock]": "Je n'aime pas",
    "13-Que penses-tu de ? [AndroidStudio]": "J'aime bien",
    "13-Que penses-tu de ? [Eclipse]": "J'aime bien",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "J'aime bien",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Connais pas",
    "13-Que penses-tu de ? [Ionic]": "Je n'aime pas"
  },
  {
    "Timestamp": "2020/10/16 4:09:09 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20206022,
    "2-D'où viens tu ?": "Nouvelle-Calédonie ",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "DUT;Prépa ATS",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Oui",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Je ne sais pas",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Jhon wick",
    "7-Que fais-tu de ton temps libre ?": "Je lis des web novel, des mangas",
    "8-Quels sont tes films": {
      "séries préférées ?": "Solo leveling,jhon wick"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;HTML5 CSS;Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Jamais",
    "11-As-tu déjà utilisé ? [Mac]": "Un peu",
    "11-As-tu déjà utilisé ? [Windows]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Un peu",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "J'aime bien",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "J'aime bien",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 4:13:13 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20202888,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "DUT",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Infographie",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Garrius",
    "7-Que fais-tu de ton temps libre ?": "Lire, jouer à des jeux vidéo",
    "8-Quels sont tes films": {
      "séries préférées ?": "Interstellar"
    },
    "9-Quel est ton navigateur préféré ?": "Firefox",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;C++;HTML5 CSS;Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Régulièrement"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Un peu",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Un peu",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Un peu",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Un peu",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Un peu",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Régulièrement",
    "13-Que penses-tu de ? [Visual studio]": "J'aime bien",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "J'aime bien",
    "13-Que penses-tu de ? [Unity]": "J'aime bien",
    "13-Que penses-tu de ? [UnrealEngine]": "J'aime bien",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "J'aime bien",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 4:13:15 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 197264,
    "2-D'où viens tu ?": "Cameroun",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Licence",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Jensim;ENSIMIEN;ENSIM'Elec",
    "5-Plutôt...": "Apple",
    "6-Quel est ton personnage de fiction préféré ?": "Wonder Woman ",
    "7-Que fais-tu de ton temps libre ?": "Je médite ",
    "8-Quels sont tes films": {
      "séries préférées ?": "The catch"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Jamais",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Un peu",
    "13-Que penses-tu de ? [Visual studio]": "J'aime bien",
    "13-Que penses-tu de ? [NotePad++]": "Connais pas",
    "13-Que penses-tu de ? [Codblock]": "Je suis fan",
    "13-Que penses-tu de ? [AndroidStudio]": "J'aime bien",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Connais pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 4:27:28 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20205281,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "BTS",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Jensim",
    "5-Plutôt...": "Apple;Android",
    "6-Quel est ton personnage de fiction préféré ?": "Ironman",
    "7-Que fais-tu de ton temps libre ?": "Netflix, babbel, mooc, ...",
    "8-Quels sont tes films": {
      "séries préférées ?": " Series Marvel, films CAT8, films Hunger Games, films divergente, "
    },
    "9-Quel est ton navigateur préféré ?": "Chrome;Brave",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C#;HTML5 CSS;Php;Python;JavaScript;CMS",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Régulièrement"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Un peu",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Un peu",
    "13-Que penses-tu de ? [Visual studio]": "J'aime bien",
    "13-Que penses-tu de ? [NotePad++]": "Je n'aime pas",
    "13-Que penses-tu de ? [Codblock]": "Je n'aime pas",
    "13-Que penses-tu de ? [AndroidStudio]": "Je suis fan",
    "13-Que penses-tu de ? [Eclipse]": "Je n'aime pas",
    "13-Que penses-tu de ? [IntellJ]": "Je suis fan",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "J'aime bien",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "J'aime bien",
    "13-Que penses-tu de ? [Atom]": "Je n'aime pas",
    "13-Que penses-tu de ? [Anaconda]": "J'aime bien",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 4:45:57 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 205266,
    "2-D'où viens tu ?": "Bretagne",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "BTS",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDE;KFET",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Jack Sparrow",
    "7-Que fais-tu de ton temps libre ?": "Skate, jeux, Netflix ",
    "8-Quels sont tes films": {
      "séries préférées ?": "Fiche club/friend"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;C++",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Un peu",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Un peu",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Un peu",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "Je n'aime pas",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Je n'aime pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "J'aime bien",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Connais pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 5:01:40 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 203085,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "DUT",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Jensim;K'verne;ENSIM is Gaming",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Braum",
    "7-Que fais-tu de ton temps libre ?": "Je suis avec mes amis, je joue, je lis etc",
    "8-Quels sont tes films": {
      "séries préférées ?": "Seigneur des Anneaux, Game of Thrones, Viking"
    },
    "9-Quel est ton navigateur préféré ?": "Firefox;Opéra GX",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;C++;HTML5 CSS;Php;Python;JavaScript;Assembleur",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Régulièrement"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Un peu",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Un peu",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Un peu",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Un peu",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Régulièrement",
    "13-Que penses-tu de ? [Visual studio]": "Je suis fan",
    "13-Que penses-tu de ? [NotePad++]": "Je n'aime pas",
    "13-Que penses-tu de ? [Codblock]": "Je n'aime pas",
    "13-Que penses-tu de ? [AndroidStudio]": "J'aime bien",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "J'aime bien",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Connais pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 5:07:18 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20191920,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa classique",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDLC",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Abe no Seimei",
    "7-Que fais-tu de ton temps libre ?": "Lecture, séries, tricot",
    "8-Quels sont tes films": {
      "séries préférées ?": "Seigneur des Anneaux, Doctor Who"
    },
    "9-Quel est ton navigateur préféré ?": "Firefox",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;HTML5 CSS;Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Un peu",
    "11-As-tu déjà utilisé ? [Mac]": "Un peu",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Un peu",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "J'aime bien",
    "13-Que penses-tu de ? [Anaconda]": "J'aime bien",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/16 5:34:23 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 205371,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "DUT;1 année d'ingénieur après dut",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDE;BDLC;K'verne;Trublions du Plateau",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Gon",
    "7-Que fais-tu de ton temps libre ?": "Je regardes des vidéos",
    "8-Quels sont tes films": {
      "séries préférées ?": "Star wars, One piece, HxH"
    },
    "9-Quel est ton navigateur préféré ?": "Brave",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;HTML5 CSS;Php;Python;JavaScript;Assembleur",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Linux]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Mac]": "Un peu",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Jamais;Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Un peu",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Un peu",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Un peu",
    "13-Que penses-tu de ? [Visual studio]": "Je n'aime pas",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "Je n'aime pas",
    "13-Que penses-tu de ? [AndroidStudio]": "Je suis fan",
    "13-Que penses-tu de ? [Eclipse]": "Je n'aime pas",
    "13-Que penses-tu de ? [IntellJ]": "Je suis fan",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "J'aime bien",
    "13-Que penses-tu de ? [UnrealEngine]": "J'aime bien",
    "13-Que penses-tu de ? [SublimeText]": "Je suis fan",
    "13-Que penses-tu de ? [Atom]": "J'aime bien",
    "13-Que penses-tu de ? [Anaconda]": "J'aime bien",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/21 2:52:01 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20205195,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa classique",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "ENSIM'Elec",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Eragon",
    "7-Que fais-tu de ton temps libre ?": "Programmation et jeux vidéos ",
    "8-Quels sont tes films": {
      "séries préférées ?": "Aucuns"
    },
    "9-Quel est ton navigateur préféré ?": "Firefox;Brave",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;C++;HTML5 CSS;Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Régulièrement"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Linux]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Un peu",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Un peu",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Je n'aime pas",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "Je n'aime pas",
    "13-Que penses-tu de ? [AndroidStudio]": "J'aime bien",
    "13-Que penses-tu de ? [Eclipse]": "Je suis fan",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Je n'aime pas",
    "13-Que penses-tu de ? [UnrealEngine]": "J'aime bien",
    "13-Que penses-tu de ? [SublimeText]": "J'aime bien",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Je n'aime pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/21 5:08:45 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20182355,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "BDE;BDLC;MAO;ENSIMIEN;K'verne;VASI;ENSIM'Elec;Abobinables",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Rick Deckard",
    "7-Que fais-tu de ton temps libre ?": "Plein de choses",
    "8-Quels sont tes films": {
      "séries préférées ?": "Westworld, The eternal sunshine of the spotless mind"
    },
    "9-Quel est ton navigateur préféré ?": "Firefox",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;C++;C#;HTML5 CSS;Php;Python;JavaScript",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Régulièrement"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Un peu",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Je n'aime pas",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Je n'aime pas",
    "13-Que penses-tu de ? [Eclipse]": "Je suis fan",
    "13-Que penses-tu de ? [IntellJ]": "J'aime bien",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "J'aime bien",
    "13-Que penses-tu de ? [UnrealEngine]": "Je n'aime pas",
    "13-Que penses-tu de ? [SublimeText]": "Je suis fan",
    "13-Que penses-tu de ? [Atom]": "Je suis fan",
    "13-Que penses-tu de ? [Anaconda]": "Je suis fan",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/21 5:23:28 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20182116,
    "2-D'où viens tu ?": "France",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa intégrée",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Jensim;Trublions du Plateau;ENSIM'Elec",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Je sais pas trop ",
    "7-Que fais-tu de ton temps libre ?": "Je retrouve des amis",
    "8-Quels sont tes films": {
      "séries préférées ?": "Westworld, Handmaid's Tale, Dexter..."
    },
    "9-Quel est ton navigateur préféré ?": "Firefox;Opera",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C;HTML5 CSS;Python;JavaScript",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Jamais",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Un peu",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Connais pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/21 5:29:00 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20205886,
    "2-D'où viens tu ?": "Tunisie",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa classique",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "Jensim;KFET;ENSIM'Elec",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Killua (hxh)",
    "7-Que fais-tu de ton temps libre ?": "Jeux videos",
    "8-Quels sont tes films": {
      "séries préférées ?": "Got /Breaking bad /Lucifer/Peaky blinders/"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "C++;Python",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Un peu;Régulièrement;Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Un peu",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Jamais",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "Connais pas",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "Connais pas",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "J'aime bien",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Connais pas",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "J'aime bien",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/22 10:55:16 AM GMT+1",
    "1-Quel est ton numéro étudiant ?": 205361,
    "2-D'où viens tu ?": "Maroc",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Licence",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Non",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "ENSIM'Elec",
    "5-Plutôt...": "Apple",
    "6-Quel est ton personnage de fiction préféré ?": "Gen xmen",
    "7-Que fais-tu de ton temps libre ?": "Sport",
    "8-Quels sont tes films": {
      "séries préférées ?": "Casa de papel"
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;HTML5 CSS;Php;Python;JavaScript;Assembleur",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Jamais"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Mac]": "Un peu",
    "11-As-tu déjà utilisé ? [Windows]": "Tout le temps",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Jamais",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Régulièrement",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Un peu",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Un peu",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Jamais",
    "13-Que penses-tu de ? [Visual studio]": "Connais pas",
    "13-Que penses-tu de ? [NotePad++]": "Je n'aime pas",
    "13-Que penses-tu de ? [Codblock]": "Je suis fan",
    "13-Que penses-tu de ? [AndroidStudio]": "J'aime bien",
    "13-Que penses-tu de ? [Eclipse]": "Je suis fan",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "Je suis fan",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Je suis fan",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  },
  {
    "Timestamp": "2020/10/22 6:08:10 PM GMT+1",
    "1-Quel est ton numéro étudiant ?": 20205322,
    "2-D'où viens tu ?": "Benin",
    "3-Quel parcours avez vous fait avant d’intégrer l'ensim": "Prépa classique;Licence",
    "4-As-tu déjà passé le TOEIC ? Tu peux mettre ton score dans autre": "Oui",
    "5-Quelles sont les associations de l'ensim qui t’intéresse ?": "ENSIM'Elec",
    "5-Plutôt...": "Android",
    "6-Quel est ton personnage de fiction préféré ?": "Christian Grey ",
    "7-Que fais-tu de ton temps libre ?": "Je code ",
    "8-Quels sont tes films": {
      "séries préférées ?": "Élite "
    },
    "9-Quel est ton navigateur préféré ?": "Chrome",
    "10-Quel langage de programmation as-tu déjà utilisé ?": "Java;C;HTML5 CSS;Php;Python;JavaScript",
    "11-As-tu déjà utilisé ? [Une carte Arduino": {
      "Raspberry]": "Un peu"
    },
    "11-As-tu déjà utilisé ? [Des logiciels de retouche (Paint, Photoshop)]": "Un peu",
    "11-As-tu déjà utilisé ? [Linux]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Mac]": "Jamais",
    "11-As-tu déjà utilisé ? [Windows]": "Régulièrement",
    "11-As-tu déjà utilisé ? [Des logiciels de montage vidéo]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de CAO (solidworks)]": "Un peu",
    "11-As-tu déjà utilisé ? [Des logiciels de création de jeux vidéos (Unity, Unreal)]": "Jamais",
    "12-As-tu déjà réalisé ? [Des logos]": "Jamais",
    "12-As-tu déjà réalisé ? [Un robot]": "Jamais",
    "12-As-tu déjà réalisé ? [Une application mobile]": "Jamais",
    "12-As-tu déjà réalisé ? [Un jeu video]": "Jamais",
    "12-As-tu déjà réalisé ? [Un logiciel sur pc]": "Un peu",
    "12-As-tu déjà réalisé ? [Un système électronique (capteurs...)]": "Un peu",
    "13-Que penses-tu de ? [Visual studio]": "J'aime bien",
    "13-Que penses-tu de ? [NotePad++]": "J'aime bien",
    "13-Que penses-tu de ? [Codblock]": "J'aime bien",
    "13-Que penses-tu de ? [AndroidStudio]": "Connais pas",
    "13-Que penses-tu de ? [Eclipse]": "J'aime bien",
    "13-Que penses-tu de ? [IntellJ]": "Connais pas",
    "13-Que penses-tu de ? [LabView]": "Connais pas",
    "13-Que penses-tu de ? [Unity]": "Connais pas",
    "13-Que penses-tu de ? [UnrealEngine]": "Connais pas",
    "13-Que penses-tu de ? [SublimeText]": "J'aime bien",
    "13-Que penses-tu de ? [Atom]": "Connais pas",
    "13-Que penses-tu de ? [Anaconda]": "Je n'aime pas",
    "13-Que penses-tu de ? [Ionic]": "Connais pas"
  }
];







  title = 'ASTRE-IPS';

  Scores: number[] = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
  Etudiants: String[] = [];

  hypothese: string;
  cover: File;

  onTitleChanged(event: any) {
    this.hypothese = event.target.value;
  }


  newBook() {
    const uploadData = new FormData();
    uploadData.append('title', this.title);
    console.log(JSON.stringify(this.Questions));
    console.log(this.Questions);
    console.log(this.Questions[0]);
  }
}
